AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.8
    Timeout: 600
    Handler: app.lambda_handler
    Architectures:
      - arm64            

Parameters:
  Project:
    Type: String
    Default: "audit-remediation"

Resources:
  CheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-check-assume-role"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-controltower-AuditAdministratorRole"
      CodeUri: src/check_assume_role

Outputs:
  CheckFunction:
    Description: "Check Function ARN"
    Value: !GetAtt CheckFunction.Arn
